/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spasi.coppier;

import java.awt.Cursor;
import javax.swing.JDialog;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author SPASI Mini 1
 */
public class PanelDialogProses extends javax.swing.JPanel {

    private JDialog _dialogProses;
    /**
     * Creates new form ForDialogForm
     */
    public PanelDialogProses() {
        initComponents();
        btn_batal_copy.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    PanelDialogProses(JTextArea txt_source, JTextField txt_destination, JDialog dialogProses) {
        _dialogProses = dialogProses;
        initComponents();
        WorkerLoop wl = new WorkerLoop(txt_source,txt_destination,txt_area_info,btn_batal_copy,txt_process,txt_current);
        wl.execute();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_batal_copy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_info = new javax.swing.JTextArea();
        txt_process = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_current = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        btn_batal_copy.setText("Batal");
        btn_batal_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_copyActionPerformed(evt);
            }
        });

        txt_area_info.setColumns(20);
        txt_area_info.setRows(5);
        jScrollPane1.setViewportView(txt_area_info);

        txt_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_processActionPerformed(evt);
            }
        });

        jLabel1.setText("Copy File");

        jLabel2.setText("Finish");

        jLabel3.setText("Current Folder Copy or File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_process)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_batal_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_current)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_current, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_process, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal_copy)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batal_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_copyActionPerformed
        // TODO add your handling code here:
        _dialogProses.dispose();
    }//GEN-LAST:event_btn_batal_copyActionPerformed

    private void txt_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_processActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_processActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal_copy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_area_info;
    private javax.swing.JTextField txt_current;
    private javax.swing.JTextField txt_process;
    // End of variables declaration//GEN-END:variables
}
